Repository GoogleChromeLabs/chromium-bidi, pull requests merged in 2024-06, with the labels that each got.

#2272 ci: fix caching for Puppeteer job
  .github/workflows/puppeteer.yml
Labels: puppeteer

#2276 fix: when reconnecting, save context's url
  src/bidiMapper/modules/cdp/CdpTargetManager.ts
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
Labels: puppeteer

#2287 build(chrome): update the pinned browser version
  .browser
  package-lock.json
  package.json
  src/bidiMapper/modules/network/NetworkModuleMocks.spec.ts
  src/bidiMapper/modules/network/NetworkUtils.ts
  src/bidiMapper/modules/storage/StorageProcessor.ts
  tests/storage/test_set_cookies.py
Labels: puppeteer

#2291 ci: fix puppeteer browser caching
  .github/workflows/puppeteer.yml
Labels: puppeteer

#2289 feat: restore frame tree when reconnecting to browser
  src/bidiMapper/modules/cdp/CdpTarget.ts
Labels: automerge, puppeteer

#2294 fix: wait for default realm to be created before evaluating script
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  src/utils/Deferred.spec.ts
  src/utils/Deferred.ts
Labels: puppeteer

#2299 fix: keep radius and force of input
  src/bidiMapper/modules/input/ActionDispatcher.ts
  src/bidiMapper/modules/input/InputSource.ts
Labels: puppeteer

#2302 fix: remove requests after they have been completed
  src/bidiMapper/modules/network/NetworkRequest.ts
  tests/network/test_continue_request.py
  tests/network/test_continue_response.py
  tests/network/test_continue_with_auth.py
  tests/network/test_provide_response.py
Labels: puppeteer

#2264 fix: provide `navigation` and `url` in events
  src/bidiMapper/BidiServer.ts
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  src/bidiMapper/modules/network/NetworkRequest.ts
  src/bidiMapper/modules/network/NetworkStorage.spec.ts
  src/bidiMapper/modules/network/NetworkStorage.ts
  tests/browsing_context/test_create.py
  tests/browsing_context/test_fragment_navigated.py
  tests/browsing_context/test_navigate.py
  tests/browsing_context/test_nested_browsing_context.py
  tests/browsing_context/test_reload.py
  tests/network/test_network.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigate/hash.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/combined/network_events.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigate/hash.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/combined/network_events.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigate/hash.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/combined/network_events.py.ini
Labels: puppeteer

#2342 chore: update BiDi types
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  src/protocol-parser/generated/webdriver-bidi.ts
  src/protocol/generated/webdriver-bidi.ts
  tests/browsing_context/test_close.py
  tests/browsing_context/test_user_prompt.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
Labels: update-expectations

#2350 ci: run interop test in shareded run
  .github/workflows/wpt-quick.yml
  .github/workflows/wpt.yml
Labels: update-expectations

#2349 fix: provide type in `browsingContext.userPromptClosed` event
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  tests/browsing_context/test_user_prompt.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/user_prompt_closed/beforeunload.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/user_prompt_closed/user_prompt_closed.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_closed/beforeunload.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_closed/user_prompt_closed.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_closed/beforeunload.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_closed/user_prompt_closed.py.ini
Labels: puppeteer
