Repository GoogleChromeLabs/chromium-bidi, pull requests merged in 2024-11, with the labels that each got.

#2720 chore: respect iframe offset in input events
  src/bidiMapper/modules/input/ActionDispatcher.ts
  tests/conftest.py
  tests/input/test_input.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/input/perform_actions/pointer_mouse.py.ini
Labels: update-expectations

#2742 ci: download headless shell when needed
  tools/install-browser.mjs
  tools/path-getter/path-getter.mjs
  tools/run-e2e.mjs
Labels: automerge

#2725 test: make `test_speculationrules_prerender` stable
  tests/browsing_context/test_navigate.py
Labels: automerge

#2748 ci: install headless shell when required
  .github/workflows/e2e.yml
  .github/workflows/selenium.yml
  .github/workflows/webdriverio.yml
  .github/workflows/wpt.yml
  tools/install-browser.mjs
Labels: automerge

#2770 test: disable HttpsFirstBalancedModeAutoEnable
  src/bidiServer/BrowserInstance.ts
Labels: automerge

#2780 feat: implement `browser.getClientWindows`
  src/bidiMapper/CommandProcessor.ts
  src/bidiMapper/modules/browser/BrowserProcessor.ts
  tests/browser/test_get_client_windows.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browser/get_client_windows/get_client_windows.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browser/get_client_windows/get_client_windows.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browser/get_client_windows/get_client_windows.py.ini
Labels: update-expectations

#2805 build(chrome): update the pinned browser version to 133.0.6851.0
  .browser
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
Labels: puppeteer, update-expectations

#2796 feat: do not emit initial navigation events
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  src/utils/UrlHelpers.spec.ts
  src/utils/UrlHelpers.ts
  tests/browsing_context/test_create.py
  tests/browsing_context/test_dom_content_loaded.py
  tests/browsing_context/test_load.py
  tests/browsing_context/test_navigate.py
  tests/script/test_add_preload_script.py
  tests/test_helpers.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/dom_content_loaded/dom_content_loaded.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/load/load.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/dom_content_loaded/dom_content_loaded.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/load/load.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/dom_content_loaded/dom_content_loaded.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/load/load.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
Labels: update-expectations

#2823 chore: fix type errors not getting reported
  src/bidiMapper/modules/network/NetworkRequest.ts
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/add_intercept/phase_auth_required.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/add_intercept/phases.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/before_request_sent/before_request_sent_cached.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/combined/network_events.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/continue_request/headers.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/continue_request/method.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/fail_request/request.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/fetch_error/fetch_error.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_completed/response_completed_cached.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_started/response_started.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_started/response_started_cached.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/add_intercept/phase_auth_required.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/add_intercept/phases.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent_cached.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/combined/network_events.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/continue_request/headers.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/continue_request/method.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/fail_request/request.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/fetch_error/fetch_error.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_completed/response_completed_cached.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/response_started_cached.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/add_intercept/phase_auth_required.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/add_intercept/phases.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent_cached.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/combined/network_events.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/continue_request/headers.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/continue_request/method.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/fail_request/request.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/fetch_error/fetch_error.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_completed/response_completed_cached.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/response_started_cached.py.ini
Labels: update-expectations
