Repository GoogleChromeLabs/chromium-bidi, pull requests merged in 2024-08, with the labels that each got.

#2482 build(chrome): update the pinned browser version to 129.0.6642.0
  .browser
  package-lock.json
  package.json
Labels: dependencies, update-expectations

#2486 fix: emit realm events when subscribing
  src/bidiMapper/CommandProcessor.ts
  src/bidiMapper/modules/script/ScriptProcessor.ts
Labels: puppeteer

#2483 fix: always provide url in `browsingContext.navigationStarted`
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  tests/browsing_context/test_navigate.py
Labels: automerge, puppeteer
