Repository GoogleChromeLabs/chromium-bidi, pull requests merged in 2024-12, with the labels that each got.

#2878 chore: (no-op) move navigation logic to NavigationTracker
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  src/bidiMapper/modules/context/NavigationTracker.ts
  src/utils/time.spec.ts
  src/utils/time.ts
Labels: automerge, update-expectations

#2879 chore: emulate `frameStartedNavigating` event
  src/bidiMapper/modules/cdp/CdpTarget.ts
  src/bidiMapper/modules/cdp/TargetEvents.ts
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  src/cdp/CdpClient.ts
  tests/network/test_network.py
Labels: puppeteer

#2893 test: split puppeteer tests into 4 shards
  .github/workflows/puppeteer.yml
Labels: puppeteer

#2892 test: make puppeteer tests required on releases
  .github/workflows/labeler.yml
  .github/workflows/puppeteer.yml
Labels: puppeteer, puppeteer-required

#2881 chore: refactor navigation
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  src/bidiMapper/modules/context/NavigationTracker.spec.ts
  src/bidiMapper/modules/context/NavigationTracker.ts
  tests/browsing_context/__snapshots__/test_navigate_events.ambr
  tests/browsing_context/test_create.py
  tests/browsing_context/test_dom_content_loaded.py
  tests/browsing_context/test_load.py
  tests/browsing_context/test_navigate.py
  tests/browsing_context/test_navigate_events.py
  tests/browsing_context/test_nested_browsing_context.py
  tests/browsing_context/test_print.py
  tests/conftest.py
  tests/input/test_input.py
  tests/script/test_add_preload_script.py
  tests/session/test_subscription.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
Labels: puppeteer, update-expectations

#2545 test: unmark flaky from `test_non_printable_key_sends_events`
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
Labels: automerge

#2903 build(chrome): update the pinned browser version to 133.0.6901.0
  .browser
  package-lock.json
  package.json
  tests/network/test_network.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/close/prompt_unload.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/close/prompt_unload.py.ini
Labels: update-expectations

#2898 feat: abort navigation only after frame navigated
  src/bidiMapper/modules/context/NavigationTracker.spec.ts
  src/bidiMapper/modules/context/NavigationTracker.ts
  tests/browsing_context/__snapshots__/test_navigate_events.ambr
  tests/browsing_context/test_navigate_events.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigation_failed/navigation_failed.py.ini
Labels: update-expectations

#2905 test: mark flaky from `test_non_printable_key_sends_events`
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/key_events.py.ini
Labels: automerge

#2919 feat: provide proper network timings
  .github/workflows/e2e.yml
  .github/workflows/selenium.yml
  .github/workflows/webdriverio.yml
  .github/workflows/wpt.yml
  src/bidiMapper/modules/context/NavigationTracker.spec.ts
  src/bidiMapper/modules/network/NetworkRequest.ts
  src/bidiMapper/modules/network/NetworkUtils.ts
  tests/network/test_network.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_started/response_started.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
Labels: update-expectations
