Repository GoogleChromeLabs/chromium-bidi, pull requests merged in 2025-02, with the labels that each got.

#3066 refactor: extract logic for userContext verification
  src/bidiMapper/CommandProcessor.ts
  src/bidiMapper/modules/browser/UserContextStorage.ts
  src/bidiMapper/modules/context/BrowsingContextStorage.ts
  src/bidiMapper/modules/script/ScriptProcessor.ts
  src/bidiMapper/modules/session/EventManager.ts
  src/bidiMapper/modules/session/SubscriptionManager.ts
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/script/add_preload_script/invalid.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/add_preload_script/invalid.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/script/add_preload_script/invalid.py.ini
Labels: update-expectations

#3077 ci: provide a PR number in update the expectations PR
  .github/workflows/wpt.yml
Labels: update-expectations

#3072 feat: support UserContext in PreloadScripts
  src/bidiMapper/modules/browser/UserContextStorage.ts
  src/bidiMapper/modules/cdp/CdpTarget.ts
  src/bidiMapper/modules/cdp/CdpTargetManager.ts
  src/bidiMapper/modules/script/PreloadScript.ts
  src/bidiMapper/modules/script/PreloadScriptStorage.spec.ts
  src/bidiMapper/modules/script/PreloadScriptStorage.ts
  src/bidiMapper/modules/script/ScriptProcessor.ts
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/script/add_preload_script/user_contexts.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/script/add_preload_script/user_contexts.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/script/add_preload_script/user_contexts.py.ini
Labels: puppeteer, update-expectations

#3086 feat: wait `none` waits for navigation to be committed
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  src/bidiMapper/modules/context/NavigationTracker.ts
  tests/browsing_context/__snapshots__/test_navigate_events.ambr
  tests/browsing_context/test_navigate.py
  tests/browsing_context/test_navigate_events.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigate/navigate.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/reload/wait.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/fetch_error/fetch_error.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigate/navigate.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/reload/wait.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/fetch_error/fetch_error.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigate/navigate.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/navigation_started/navigation_started.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/reload/wait.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/fetch_error/fetch_error.py.ini
Labels: automerge, update-expectations

#3123 build(chrome): update the pinned browser version to 135.0.7021.0
  .browser
  package-lock.json
  package.json
  tests/network/test_continue_request.py
  wpt-metadata/mapper/headless/webdriver/tests/bidi/external/bluetooth/simulate_adapter/state.py.ini
Labels: update-expectations

#3127 build(spec): update WebDriverBiDi types
  src/protocol-parser/generated/webdriver-bidi.ts
  src/protocol/generated/webdriver-bidi.ts
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/input/perform_actions/invalid.py.ini
Labels: update-expectations

#3137 fix: hide cdp.send after the mapper receives it
  src/bidiTab/Transport.ts
Labels: automerge

#3149 build(spec): update WebDriverBiDi types
  src/bidiMapper/modules/bluetooth/BluetoothProcessor.ts
  src/protocol-parser/generated/webdriver-bidi-bluetooth.ts
  src/protocol/generated/webdriver-bidi-bluetooth.ts
  tests/bluetooth/test_emulation.py
  tests/conftest.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/external/bluetooth/simulate_adapter/invalid.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/external/bluetooth/simulate_adapter/state.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/external/bluetooth/simulate_preconnected_peripheral/simulate_preconnected_peripheral.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/external/bluetooth/simulate_adapter/invalid.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/external/bluetooth/simulate_adapter/state.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/external/bluetooth/simulate_preconnected_peripheral/simulate_preconnected_peripheral.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/external/bluetooth/simulate_adapter/invalid.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/external/bluetooth/simulate_adapter/state.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/external/bluetooth/simulate_preconnected_peripheral/simulate_preconnected_peripheral.py.ini
Labels: update-expectations

#3012 feat: webExtension module
  src/bidiMapper/BidiNoOpParser.ts
  src/bidiMapper/BidiParser.ts
  src/bidiMapper/CommandProcessor.ts
  src/bidiMapper/modules/webExtension/WebExtensionProcessor.ts
  src/bidiServer/BrowserInstance.ts
  src/bidiServer/MapperCdpConnection.ts
  src/bidiServer/PipeTransport.ts
  src/bidiTab/BidiParser.ts
  src/protocol-parser/protocol-parser.ts
  tests/conftest.py
  tests/webExtension/test_web_extension.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/web_extension/install/invalid.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/web_extension/uninstall/invalid.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/web_extension/install/invalid.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/web_extension/uninstall/invalid.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/web_extension/install/invalid.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/web_extension/uninstall/invalid.py.ini
Labels: implementation, automerge, update-expectations

#3169 fix: update handling of extension data types
  src/bidiMapper/modules/webExtension/WebExtensionProcessor.ts
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/web_extension/install/invalid.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/web_extension/install/invalid.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/web_extension/install/invalid.py.ini
Labels: update-expectations
