Repository GoogleChromeLabs/chromium-bidi, pull requests merged in 2025-04, with the labels that each got.

#3311 feat: implement `emulation.setGeolocationOverride`
  src/bidiMapper/BidiNoOpParser.ts
  src/bidiMapper/BidiParser.ts
  src/bidiMapper/CommandProcessor.ts
  src/bidiMapper/modules/browser/UserContextConfig.ts
  src/bidiMapper/modules/cdp/CdpTarget.ts
  src/bidiMapper/modules/emulation/EmulationProcessor.ts
  src/bidiTab/BidiParser.ts
  src/protocol-parser/protocol-parser.ts
  tests/emulation/__snapshots__/test_geolocation.ambr
  tests/emulation/test_geolocation.py
  tests/permissions/__init__.py
  tests/permissions/test_set_permission.py
  tests/test_helpers.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/emulation/set_geolocation_override/invalid.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/emulation/set_geolocation_override/user_contexts.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/emulation/set_geolocation_override/invalid.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/emulation/set_geolocation_override/user_contexts.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/emulation/set_geolocation_override/invalid.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/emulation/set_geolocation_override/user_contexts.py.ini
Labels: update-expectations

#3318 fix: string `unhandledPromptBehavior` capability implies `beforeUnload: accept` behavior
  src/bidiMapper/modules/session/SessionProcessor.ts
  tests/browsing_context/test_user_prompt.py
  wpt-metadata/chromedriver/headful/webdriver/tests/interop/beforeunload_prompt.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/interop/beforeunload_prompt.py.ini
Labels: DO NOT MERGE, update-expectations

#3323 chore: update README.md
  README.md
Labels: automerge

#3326 fix: allow esm imports
  package.json
Labels: puppeteer

#3349 feat: provide proper context id in `browsingContext.userPrompt`
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  tests/browsing_context/test_user_prompt.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/user_prompt_closed/user_prompt_closed.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_closed/user_prompt_closed.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_closed/user_prompt_closed.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py.ini
Labels: puppeteer, update-expectations

#3359 feat: emulate geolocation positionUnavailable
  src/bidiMapper/modules/browser/UserContextConfig.ts
  src/bidiMapper/modules/cdp/CdpTarget.ts
  src/bidiMapper/modules/emulation/EmulationProcessor.ts
  src/protocol-parser/generated/webdriver-bidi.ts
  src/protocol-parser/protocol-parser.ts
  src/protocol/generated/webdriver-bidi.ts
  tests/emulation/__snapshots__/test_geolocation.ambr
  tests/emulation/test_geolocation.py
Labels: update-expectations
