Repository GoogleChromeLabs/chromium-bidi, pull requests merged in 2025-01, with the labels that each got.

#2947 feat: heuristic for request's `initiatorType` and `destination`
  src/bidiMapper/modules/network/NetworkRequest.ts
  tests/network/test_network.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/response_started/response_started.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/before_request_sent/before_request_sent.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_completed/response_completed.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/response_started/response_started.py.ini
Labels: update-expectations

#2963 chore: use Node v22 for infra
  .github/workflows/puppeteer.yml
  .nvmrc
Labels: puppeteer

#2964 fix: wait for fragment navigation to finish before finishing navigation command
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  src/bidiMapper/modules/context/NavigationTracker.ts
  tests/browsing_context/test_navigate.py
  tests/conftest.py
  tests/tools/test_local_http_server.py
Labels: puppeteer

#2968 feat: implement context locator
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/locate_nodes/locator.py.ini
Labels: automerge, update-expectations

#2987 fix: multi headers reporting incorrectly
  src/bidiMapper/modules/network/NetworkRequest.ts
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/network/continue_request/headers.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/network/continue_request/headers.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/network/continue_request/headers.py.ini
Labels: update-expectations

#2996 feat: support `goog:channel` along with `channel`
  src/bidiMapper/BidiServer.ts
  src/bidiMapper/OutgoingMessage.ts
  src/bidiMapper/modules/network/NetworkStorage.spec.ts
  src/bidiMapper/modules/session/EventManager.ts
  src/bidiMapper/modules/session/SessionProcessor.ts
  src/bidiMapper/modules/session/SubscriptionManager.spec.ts
  src/bidiMapper/modules/session/SubscriptionManager.ts
  src/bidiTab/Transport.ts
  src/protocol/chromium-bidi.ts
  tests/session/test_subscription.py
  tests/test_helpers.py
Labels: BiDi+

#2998 fix: wait for context should respect already existing contexts
  src/bidiMapper/modules/context/BrowsingContextStorage.ts
Labels: puppeteer

#3027 fix: handle max depth property
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  tests/browsing_context/test_close.py
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/context_destroyed/context_destroyed.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/context_destroyed/context_destroyed.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/context_destroyed/context_destroyed.py.ini
Labels: update-expectations

#3029 fix: rely on frameSubtreeWillBeDetached to emit contextDestroyed events
  src/bidiMapper/modules/cdp/CdpTargetManager.ts
  src/bidiMapper/modules/context/BrowsingContextImpl.ts
  wpt-metadata/chromedriver/headful/webdriver/tests/bidi/browsing_context/context_destroyed/context_destroyed.py.ini
  wpt-metadata/chromedriver/headless/webdriver/tests/bidi/browsing_context/context_destroyed/context_destroyed.py.ini
  wpt-metadata/mapper/headless/webdriver/tests/bidi/browsing_context/context_destroyed/context_destroyed.py.ini
Labels: puppeteer, update-expectations
